[package]
name = "dapr-rust"
version = "0.1.0"
authors = ["Jan Tschada <jts@esri-de.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dapr = "0.2.0-alpha.0"
